config/routes.rb
GannettMonitor::Engine.routes.draw do
  resources :application_states
  root to: "application_states#index"
end

app/models/gannett_monitor/application_state.rb
module GannettMonitor
  class ApplicationState < ActiveRecord::Base
  end
end

app/controllers/gannett_monitor/application_controller.rb
module GannettMonitor
  class ApplicationController < ActionController::Base
  end
end

app/controllers/gannett_monitor/application_states_controller.rb
require_dependency "gannett_monitor/application_controller"

module GannettMonitor
  class ApplicationStatesController < ApplicationController
    before_action :set_application_state, only: [:show, :edit, :update, :destroy]

    # GET /application_states
    def index
      @application_states = ApplicationState.all
    end

    # GET /application_states/1
    def show
    end

    # GET /application_states/new
    def new
      @application_state = ApplicationState.new
    end

    # GET /application_states/1/edit
    def edit
    end

    # POST /application_states
    def create
      @application_state = ApplicationState.new(application_state_params)

      if @application_state.save
        redirect_to @application_state, notice: 'Application state was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /application_states/1
    def update
      if @application_state.update(application_state_params)
        redirect_to @application_state, notice: 'Application state was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /application_states/1
    def destroy
      @application_state.destroy
      redirect_to application_states_url, notice: 'Application state was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_application_state
        @application_state = ApplicationState.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def application_state_params
        params.require(:application_state).permit(:name)
      end
  end
end

app/helpers/gannett_monitor/application_helper.rb
module GannettMonitor
  module ApplicationHelper
  end
end

app/helpers/gannett_monitor/application_states_helper.rb
module GannettMonitor
  module ApplicationStatesHelper
  end
end

app/views/gannett_monitor/application_states/_form.html.erb
<%= form_for(@application_state) do |f| %>
  <% if @application_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application_state.errors.count, "error") %> prohibited this application_state from being saved:</h2>

      <ul>
      <% @application_state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gannett_monitor/application_states/edit.html.erb
<h1>Editing application_state</h1>

<%= render 'form' %>

<%= link_to 'Show', @application_state %> |
<%= link_to 'Back', application_states_path %>

app/views/gannett_monitor/application_states/index.html.erb
<h1>Listing application_states</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @application_states.each do |application_state| %>
      <tr>
        <td><%= application_state.name %></td>
        <td><%= link_to 'Show', application_state %></td>
        <td><%= link_to 'Edit', edit_application_state_path(application_state) %></td>
        <td><%= link_to 'Destroy', application_state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application state', new_application_state_path %>

app/views/gannett_monitor/application_states/new.html.erb
<h1>New application_state</h1>

<%= render 'form' %>

<%= link_to 'Back', application_states_path %>

app/views/gannett_monitor/application_states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @application_state.name %>
</p>

<%= link_to 'Edit', edit_application_state_path(@application_state) %> |
<%= link_to 'Back', application_states_path %>

app/views/layouts/gannett_monitor/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GannettMonitor</title>
  <%= stylesheet_link_tag    "gannett_monitor/application", media: "all" %>
  <%= javascript_include_tag "gannett_monitor/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>